# Generated by Django 3.2.5 on 2022-04-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_company_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criar_usuario', models.BooleanField(blank=True, default=False)),
                ('editar_usuario', models.BooleanField(blank=True, default=False)),
                ('excluir_usuario', models.BooleanField(blank=True, default=False)),
                ('ver_usuario', models.BooleanField(blank=True, default=False)),
                ('criar_categoria', models.BooleanField(blank=True, default=False)),
                ('editar_categoria', models.BooleanField(blank=True, default=False)),
                ('excluir_categoria', models.BooleanField(blank=True, default=False)),
                ('ver_categoria', models.BooleanField(blank=True, default=False)),
                ('criar_produto', models.BooleanField(blank=True, default=False)),
                ('editar_produto', models.BooleanField(blank=True, default=False)),
                ('excluir_produto', models.BooleanField(blank=True, default=False)),
                ('ver_produto', models.BooleanField(blank=True, default=False)),
                ('criar_pedido', models.BooleanField(blank=True, default=False)),
                ('editar_pedido', models.BooleanField(blank=True, default=False)),
                ('excluir_pedido', models.BooleanField(blank=True, default=False)),
                ('ver_pedido', models.BooleanField(blank=True, default=False)),
                ('criar_empresa', models.BooleanField(blank=True, default=False)),
                ('editar_empresa', models.BooleanField(blank=True, default=False)),
                ('excluir_empresa', models.BooleanField(blank=True, default=False)),
                ('ver_empresa', models.BooleanField(blank=True, default=False)),
                ('criar_perfil', models.BooleanField(blank=True, default=False)),
                ('editar_perfil', models.BooleanField(blank=True, default=False)),
                ('excluir_perfil', models.BooleanField(blank=True, default=False)),
                ('ver_perfil', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
