# Generated by Django 3.2.5 on 2022-06-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20220429_1212'),
        ('pedido', '0002_auto_20220621_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='item',
            field=models.ManyToManyField(blank=True, to='item.Item'),
        ),
    ]
