# Generated by Django 3.2.5 on 2022-06-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deleta_pedidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='historico_pedidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='loja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='produto',
            field=models.BooleanField(default=False),
        ),
    ]
