# Generated by Django 3.2.5 on 2022-04-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissoes', '0001_initial'),
        ('user', '0002_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='permissoes.perfil'),
        ),
    ]
