# Generated by Django 3.2.5 on 2022-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, default='000.000.000-00', max_length=14, null=True),
        ),
    ]
