# Generated by Django 3.2.5 on 2022-04-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('numero_endereco', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
