# Generated by Django 3.2.5 on 2022-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
