# Generated by Django 3.2.6 on 2021-08-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='preco',
        ),
    ]
