# Generated by Django 3.2.5 on 2021-08-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('categoria', '0003_alter_category_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.store'),
        ),
    ]
