# Generated by Django 3.2.5 on 2022-04-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_cnpj'),
        ('categoria', '0004_alter_category_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='loja',
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company'),
        ),
    ]
