# Generated by Django 3.2.6 on 2021-08-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='preco',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
