# Generated by Django 3.2.5 on 2021-08-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('item', '0003_alter_item_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.store'),
        ),
    ]
