# Generated by Django 3.2.5 on 2021-08-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='preco',
        ),
    ]
