# Generated by Django 3.2.5 on 2022-04-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code_bar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='valor_custo',
            field=models.BooleanField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='valor_venda',
            field=models.BooleanField(blank=True, max_length=10, null=True),
        ),
    ]
