# Generated by Django 3.2.5 on 2022-04-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20220418_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valor_custo',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='valor_venda',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
